- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: ''  # Use the sha you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflicts
- repo: git://github.com/pricematch/mirrors-rubocop
  sha: ''  # Use the sha you want to point at
  hooks:
    - id: rubocop
