- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 'master'  # Use the sha you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-merge-conflict
- repo: git://github.com/pricematch/mirrors-rubocop
  sha: '64f42a367'  # Use the sha you want to point at
  hooks:
    - id: rubocop
